### ISSUE TITLE
GitHub class conflict

### ISSUE THREAD

**Issue by pzcode** [FRC2832/Robot_2017#4]
Why are we getting Class conflicts when Pull, and how do we resolve so we can get the code.

**Comment by pzcode** [comment]
Dillan showed me how how to Reset, but took several steps.  You may need to check with him.

**Comment by Dactaxx** [comment]
Steps:
     • Commit all changes
     • Reset from the desired branch under the            remote folder.

**Comment by pzcode** [comment]
Setup your User Library paths as described in this file - [Variable Library](https://docs.google.com/document/d/18XQoKHcclQci89FtwhT6HkhnJgU_jLoMZhEPn0fiR4w/edit)

Load 3rd party libraries following [these instructions](https://docs.google.com/document/d/1CWgUaXvGs5DWKJsRpliLuLOjwtjrkch2yzTUFZmJBCY/edit)
